version: '3'
 
services:

    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.nginx
        ports:
            - "80:80"
            - "443:443"
        networks:
            - appnetwork_nginx

networks:
    appnetwork_nginx:
        driver: bridge